import { useState } from 'react'
import { Edit3, Plus, Trash2, X } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useProducts } from '../hooks/useProducts'
import type { Product } from '../types/product'

type Draft = Omit<Product, 'id'>
const emptyDraft: Draft = { name: '', category: '', price: 0, images: [''], description: '', sizes: [], featured: false }
const currency = new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 })

export function AdminProducts() {
  const { products, createProduct, updateProduct, deleteProduct } = useProducts()
  const [editing, setEditing] = useState<Product | null>(null)
  const [showForm, setShowForm] = useState(false)
  const [draft, setDraft] = useState<Draft>(emptyDraft)
  const openForm = (product?: Product) => { setEditing(product ?? null); setDraft(product ? { name: product.name, category: product.category, price: product.price, images: product.images, description: product.description, sizes: product.sizes ?? [], featured: product.featured } : emptyDraft); setShowForm(true) }
  const updateImage = (index: number, value: string) => setDraft((current) => ({ ...current, images: current.images.map((image, imageIndex) => imageIndex === index ? value : image) }))
  const closeForm = () => { setShowForm(false); setEditing(null); setDraft(emptyDraft) }
  const save = (event: React.FormEvent) => { event.preventDefault(); const clean = { ...draft, images: draft.images.filter(Boolean), sizes: draft.sizes.filter(Boolean) }; if (!clean.name || !clean.category || !clean.description || !clean.images.length || !clean.sizes.length) return; if (editing) updateProduct(editing.id, clean); else createProduct(clean); closeForm() }
  return <div className="min-h-screen bg-stone-100 p-5 sm:p-10"><main className="mx-auto max-w-6xl"><div className="flex flex-wrap items-center justify-between gap-5"><div><p className="text-xs font-medium uppercase tracking-[0.2em] text-amber-800">Administración</p><h1 className="mt-2 font-serif text-4xl text-stone-950">Productos</h1></div><div className="flex gap-3"><Link className="border border-stone-300 px-4 py-3 text-sm" to="/">Ver tienda</Link><button onClick={() => openForm()} className="inline-flex items-center gap-2 bg-stone-900 px-4 py-3 text-sm font-medium text-white"><Plus size={17}/> Nuevo producto</button></div></div>
  <div className="mt-10 overflow-x-auto bg-white shadow-sm"><table className="w-full min-w-165 text-left text-sm"><thead className="border-b border-stone-200 text-xs uppercase tracking-wider text-stone-500"><tr><th className="p-4">Producto</th><th className="p-4">Categoría</th><th className="p-4">Tallas</th><th className="p-4">Precio</th><th className="p-4">Imágenes</th><th className="p-4 text-right">Acciones</th></tr></thead><tbody>{products.map((product) => <tr className="border-b border-stone-100" key={product.id}><td className="flex items-center gap-3 p-4 font-medium text-stone-900"><img className="h-12 w-10 object-cover" src={product.images[0]} alt=""/>{product.name}</td><td className="p-4 text-stone-600">{product.category}</td><td className="p-4 text-stone-600">{product.sizes?.join(', ')}</td><td className="p-4 text-stone-600">{product.price > 0 ? currency.format(product.price) : 'Por definir'}</td><td className="p-4 text-stone-600">{product.images.length}</td><td className="p-4"><div className="flex justify-end gap-3"><button aria-label={`Editar ${product.name}`} onClick={() => openForm(product)}><Edit3 size={17}/></button><button aria-label={`Eliminar ${product.name}`} onClick={() => { if (confirm(`¿Eliminar ${product.name}?`)) deleteProduct(product.id) }} className="text-red-700"><Trash2 size={17}/></button></div></td></tr>)}</tbody></table></div>
  {showForm && <div className="fixed inset-0 z-10 overflow-y-auto bg-stone-950/35 p-4"><form onSubmit={save} className="mx-auto my-8 max-w-2xl bg-white p-6 shadow-xl sm:p-8"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-wider text-amber-800">Administrador</p><h2 className="mt-1 font-serif text-3xl">{editing ? 'Editar producto' : 'Nuevo producto'}</h2></div><button type="button" onClick={closeForm}><X /></button></div><div className="mt-7 grid gap-5 sm:grid-cols-2"><Field label="Nombre"><input required value={draft.name} onChange={(e) => setDraft({...draft, name:e.target.value})}/></Field><Field label="Categoría"><input required value={draft.category} onChange={(e) => setDraft({...draft, category:e.target.value})}/></Field><Field label="Precio (COP)"><input required min="0" type="number" value={draft.price || ''} onChange={(e) => setDraft({...draft, price:Number(e.target.value)})}/></Field><Field label="Tallas disponibles"><input required placeholder="XS, SM, LXL, XXL" value={draft.sizes.join(', ')} onChange={(e) => setDraft({...draft, sizes: e.target.value.split(',').map((size) => size.trim().toUpperCase())})}/></Field><label className="flex items-end gap-2 pb-3 text-sm"><input type="checkbox" checked={draft.featured} onChange={(e) => setDraft({...draft, featured:e.target.checked})}/> Producto destacado</label></div><Field label="Descripción"><textarea required rows={3} value={draft.description} onChange={(e) => setDraft({...draft, description:e.target.value})}/></Field><div className="mt-5"><p className="text-sm font-medium text-stone-800">Imágenes del producto</p><p className="mt-1 text-xs text-stone-500">Por ahora agrega URLs. Firebase Storage reemplazará este paso al conectarlo.</p><div className="mt-3 space-y-2">{draft.images.map((image, index) => <div className="flex gap-2" key={index}><input required className="w-full border border-stone-300 px-3 py-2 text-sm outline-none focus:border-stone-900" placeholder="https://..." value={image} onChange={(e) => updateImage(index, e.target.value)}/>{draft.images.length > 1 && <button type="button" className="px-2 text-red-700" onClick={() => setDraft({...draft, images:draft.images.filter((_, imageIndex) => imageIndex !== index)})}><Trash2 size={16}/></button>}</div>)}</div><button type="button" className="mt-3 text-sm underline" onClick={() => setDraft({...draft, images:[...draft.images, '']})}>+ Agregar otra imagen</button></div><button className="mt-8 w-full bg-stone-900 py-3 text-sm font-medium text-white">Guardar producto</button></form></div>}</main></div>
}

function Field({ label, children }: { label: string, children: React.ReactNode }) { return <label className="mt-5 block text-sm font-medium text-stone-800">{label}<span className="mt-2 block [&_input]:w-full [&_input]:border [&_input]:border-stone-300 [&_input]:px-3 [&_input]:py-2 [&_input]:font-normal [&_textarea]:w-full [&_textarea]:border [&_textarea]:border-stone-300 [&_textarea]:px-3 [&_textarea]:py-2 [&_textarea]:font-normal">{children}</span></label> }
